# docker-compose.yml
version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend # Docker Compose will use the multi-stage Dockerfile
    ports:
      - "3000:80" # Map host port 3000 to container port 80 (where Nginx serves)
    environment:
      - NUXT_API_URL=http://backend:8000